<a href="https://colab.research.google.com/github/ashunni99/Datasets/blob/main/wine_quality_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **WINE QUALITY PREDICTION**

Imported necessary functions and the dataset

In [123]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/WineQT.csv')
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1138            6.3             0.510         0.13             2.3      0.076   
1139            6.8             0.620         0.08             1.9      0.068   
1140            6.2             0.600         0.08             2.0      0.090   
1141            5.9             0.550         0.10             2.2      0.062   
1142            5.9             0.645         0.12             2.0      0.075   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1138                 29.0                  40.0  0.99574  3.42       0.75   
1139                 28.0                  38.0  0.99651  3.42       0.82   
1140                 32.0                  44.0  0.99490  3.45       0.58   
1141                 39.0                  51.0  0.99512  3.52       0.76   
1142                 32.0                  44.0  0.99547  3.57       0.71   

      alcohol  quality    Id  
0         9.4        5     0  
1         9.8        5     1  
2         9.8        5     2  
3         9.8        6     3  
4         9.4        5     4  
...       ...      ...   ...  
1138     11.0        6  1592  
1139      9.5        6  1593  
1140     10.5        5  1594  
1141     11.2        6  1595  
1142     10.2        5  1597  

[1143 rows x 13 columns]

Checking for missing values if any

In [124]:
df.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
Id                      0
dtype: int64

Checking for the datatype of each feature

In [125]:
df.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
Id                        int64
dtype: object

Splitting input 'x' and output 'y' from the dataset

In [126]:
x=df.drop('quality',axis=1).values
x

array([[7.400e+00, 7.000e-01, 0.000e+00, ..., 5.600e-01, 9.400e+00,
        0.000e+00],
       [7.800e+00, 8.800e-01, 0.000e+00, ..., 6.800e-01, 9.800e+00,
        1.000e+00],
       [7.800e+00, 7.600e-01, 4.000e-02, ..., 6.500e-01, 9.800e+00,
        2.000e+00],
       ...,
       [6.200e+00, 6.000e-01, 8.000e-02, ..., 5.800e-01, 1.050e+01,
        1.594e+03],
       [5.900e+00, 5.500e-01, 1.000e-01, ..., 7.600e-01, 1.120e+01,
        1.595e+03],
       [5.900e+00, 6.450e-01, 1.200e-01, ..., 7.100e-01, 1.020e+01,
        1.597e+03]])

In [127]:
y=df['quality'].values
y

array([5, 5, 5, ..., 5, 6, 5])

Checking for the diamension of input 'x'

In [128]:
x.ndim

2

Checking for the diamension of output 'y'

In [129]:
y.ndim

1

Performing train_test_split from the input and output

In [130]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
y_train

array([5, 5, 3, 6, 5, 5, 7, 5, 5, 6, 6, 7, 5, 6, 6, 7, 6, 6, 5, 7, 6, 6,
       6, 7, 5, 6, 5, 5, 6, 5, 5, 5, 5, 8, 7, 6, 4, 5, 6, 7, 5, 6, 7, 6,
       6, 5, 6, 5, 6, 5, 5, 6, 6, 5, 8, 6, 6, 5, 5, 4, 6, 5, 5, 6, 5, 5,
       6, 7, 5, 6, 7, 7, 5, 6, 4, 4, 6, 5, 6, 7, 6, 6, 5, 6, 5, 6, 6, 5,
       6, 5, 5, 7, 6, 5, 5, 5, 4, 6, 6, 6, 6, 6, 6, 7, 3, 5, 5, 5, 5, 5,
       5, 5, 3, 5, 6, 6, 7, 5, 5, 6, 5, 7, 7, 6, 6, 6, 6, 4, 5, 5, 6, 5,
       5, 6, 6, 5, 6, 5, 6, 7, 5, 7, 5, 5, 6, 6, 7, 6, 6, 6, 5, 5, 6, 6,
       6, 7, 6, 6, 6, 7, 5, 5, 5, 5, 5, 7, 7, 6, 6, 5, 6, 5, 6, 8, 6, 5,
       6, 5, 6, 6, 6, 6, 5, 6, 6, 5, 5, 5, 7, 5, 5, 6, 5, 5, 7, 5, 5, 6,
       4, 4, 5, 6, 7, 6, 5, 6, 6, 5, 6, 6, 5, 5, 6, 6, 5, 5, 5, 6, 5, 6,
       6, 6, 6, 4, 6, 5, 7, 5, 5, 5, 5, 5, 6, 5, 5, 5, 7, 5, 5, 6, 5, 5,
       6, 6, 6, 7, 6, 6, 6, 5, 5, 6, 6, 5, 6, 6, 5, 5, 3, 6, 6, 5, 6, 7,
       7, 5, 6, 6, 6, 5, 5, 5, 6, 4, 6, 5, 5, 7, 6, 6, 7, 6, 6, 6, 5, 5,
       5, 5, 6, 6, 5, 5, 5, 5, 5, 4, 6, 5, 6, 5, 5,

Performing Normalization - using StandardScaler

In [131]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

Algorithm used for model creation is K Nearest Neighbor

In [132]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)

Checking for the accuracy score for the abve created model

In [133]:
from sklearn.metrics import accuracy_score
ac=accuracy_score(y_test,y_pred)
print('Accuracy score for the model is',ac)

Accuracy score for the model is 0.5364431486880467


Performing Hyper-Paramenter

In [134]:
from sklearn.model_selection import GridSearchCV
knn1=KNeighborsClassifier()

In [135]:
param={'n_neighbors':[3,5,7,9],'weights':['uniform','distance']}
clf=GridSearchCV(knn1,param,cv=10,scoring='accuracy')
clf.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 6 members, which is less than n_splits=10.
  warnings.warn(


GridSearchCV(cv=10, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [3, 5, 7, 9],
                         'weights': ['uniform', 'distance']},
             scoring='accuracy')

In [136]:
print(clf.best_params_)

{'n_neighbors': 9, 'weights': 'distance'}


Assigning a new variable to KneighborsClassifier with the best tuning paramenters and checking its accuracy score

In [137]:
knn2=KNeighborsClassifier(n_neighbors=9,weights='distance')
knn2.fit(x_train,y_train)
y_pred2=knn2.predict(x_test)
acc=accuracy_score(y_test,y_pred2)
print('accuracy score after tuning is',acc)

accuracy score after tuning is 0.6268221574344023
